export  * from './events-list.component';
export  * from './event-thumbnail.component';
export  * from './shared/event.service';
export  * from './event-details/event-details.components';
export  * from './Create/create-event.component'
export  * from './Edit/edit-event.component'
export  * from './event-details/event-route-activator.service'
export  * from './events-list-resolver.service'
export  * from './event-details/CreateSession/create-session.component'
export  * from './event-details/session-list.component'
export  * from './shared/duration.pipe'